[package]
name = "programmign-bitcoin-in-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
hex = "0.4.3"
hmac = "0.12.1"
num-bigint = "0.4.6"
primitive-types = "0.13.1"
rand = "0.9.1"
sha2 = "0.10.9"
thiserror = "2.0.12"
