[package]
name = "programmign-bitcoin-in-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
lazy_static = "1.5.0"
num-bigint = "0.4.6"
primitive-types = "0.13.1"
thiserror = "2.0.12"
